# Generated by Django 2.1.1 on 2018-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_application', '0002_application_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
