# Generated by Django 2.1.1 on 2018-09-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render_application', '0003_auto_20180911_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
